f =open("anonymous.txt","r")
print(f.readlines())
print(f.readlines())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# content = f.read()
# print(content)
# for line in content:
#      print(line)
f.close()